# Generated by Django 5.0.14 on 2026-08-16 19:59

import accounts.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='users/no_image.png', upload_to='users/%Y/%m/%d/')),
                ('role', models.CharField(choices=[('ADOPTER', 'Adopter'), ('SHELTER_STAFF', 'Shelter Staff'), ('ADMIN', 'Administrator')], default='ADOPTER', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('ENGAGED', 'Engaged'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('UNDISCLOSED', 'Prefer Not to Say')], default='SINGLE', max_length=15)),
                ('residence_type', models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('STUDIO', 'Studio'), ('DUPLEX', 'Duplex'), ('OTHER', 'Other')], default='APARTMENT', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('id_image', models.ImageField(storage=accounts.storage.EncryptedFileSystemStorage(subfolder='profile_ids'), upload_to='')),
                ('address_proof', models.FileField(storage=accounts.storage.EncryptedFileSystemStorage(subfolder='profile_address_proofs'), upload_to='')),
                ('occupation', models.CharField(blank=True, max_length=50)),
                ('owned_pets_before', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unverified_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='shelters.shelter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
                'indexes': [models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx')],
            },
        ),
    ]
