# Generated by Django 5.0.14 on 2026-08-21 05:58

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='users/no_image.png', upload_to=accounts.utils.profile_image_upload_path),
        ),
    ]
