# Generated by Django 5.0.14 on 2026-08-21 06:38

import accounts.storage
import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_proof',
            field=models.FileField(storage=accounts.storage.EncryptedFileSystemStorage(subfolder='profile_address_proofs'), upload_to=accounts.utils.profile_address_proof_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_image',
            field=models.ImageField(storage=accounts.storage.EncryptedFileSystemStorage(subfolder='profile_ids'), upload_to=accounts.utils.profile_id_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/no_image.png', upload_to=accounts.utils.profile_image_upload_path),
        ),
    ]
