# Generated by Django 5.0.14 on 2026-08-22 02:50

import accounts.storage
import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_address_proof_alter_profile_id_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address_proof',
            field=models.FileField(blank=True, null=True, storage=accounts.storage.EncryptedFileSystemStorage(subfolder='profile_address_proofs'), upload_to=accounts.utils.profile_address_proof_upload_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_image',
            field=models.ImageField(blank=True, null=True, storage=accounts.storage.EncryptedFileSystemStorage(subfolder='profile_ids'), upload_to=accounts.utils.profile_id_upload_path),
        ),
    ]
