# Generated by Django 5.0.14 on 2026-08-16 19:59

import accounts.storage
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('shelter_type', models.CharField(blank=True, choices=[('NGO', 'NGO'), ('ANIMAL_RESCUE', 'Animal Rescue'), ('PRIVATE_RESCUE', 'Private Rescue'), ('FOSTER_NETWORK', 'Foster Network'), ('MUNICIPAL_SHELTER', 'Municipal Shelter')], max_length=20, null=True)),
                ('animal_types_rescued', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('RABBIT', 'Rabbit'), ('OTHER', 'Other')], max_length=20), default=list, size=None)),
                ('pet_count', models.PositiveIntegerField(default=0)),
                ('adoption_count', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Valid phone number format: '+999999999'. 10-15 digits allowed.", regex='^\\+?\\d{10,15}$')])),
                ('address', models.TextField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, unique=True)),
                ('ngo_registration_cert', models.ImageField(blank=True, null=True, storage=accounts.storage.EncryptedFileSystemStorage(subfolder='shelter_ngo_registration_certs'), upload_to='')),
                ('permit', models.FileField(null=True, storage=accounts.storage.EncryptedFileSystemStorage(subfolder='shelter_permits'), upload_to='')),
                ('address_proof', models.FileField(null=True, storage=accounts.storage.EncryptedFileSystemStorage(subfolder='shelter_address_proofs'), upload_to='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20)),
                ('year_established', models.DateField()),
                ('operational_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MONDAY', 'Mon'), ('TUESDAY', 'Tue'), ('WEDNESDAY', 'Wed'), ('THURSDAY', 'Thurs'), ('FRIDAY', 'Fri'), ('SATURDAY', 'Sat'), ('SUNDAY', 'Sun')], max_length=20), default=list, size=None)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('services_offered', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MEDICAL_CARE', 'Medical Care'), ('VAC', 'Vaccination'), ('STERILIZATION', 'Sterilization'), ('TRANSPORTATION', 'Transportation'), ('FOSTER_CARE', 'Foster Care')], max_length=20), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('inactive_reason', models.TextField(blank=True, max_length=200, null=True)),
                ('agree_to_terms', models.BooleanField(default=False)),
                ('agree_to_verification', models.BooleanField(default=False)),
                ('certify_correctness', models.BooleanField(default=False)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_shelters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ShelterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='shelters/no_image.png', upload_to='shelters/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('is_logo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shelters.shelter')),
            ],
            options={
                'verbose_name': 'Shelter Image',
                'verbose_name_plural': 'Shelter Images',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='shelterimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_logo', True)), fields=('shelter',), name='unique_logo_image'),
        ),
    ]
