# Generated by Django 5.0.14 on 2026-08-21 01:42

import accounts.storage
import shelters.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='address_proof',
            field=models.FileField(null=True, storage=accounts.storage.EncryptedFileSystemStorage(subfolder='shelter_address_proofs'), upload_to=shelters.utils.secure_document_upload_path),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='ngo_registration_cert',
            field=models.FileField(blank=True, null=True, storage=accounts.storage.EncryptedFileSystemStorage(subfolder='shelter_ngo_registration_certs'), upload_to=shelters.utils.secure_document_upload_path),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='permit',
            field=models.FileField(null=True, storage=accounts.storage.EncryptedFileSystemStorage(subfolder='shelter_permits'), upload_to=shelters.utils.secure_document_upload_path),
        ),
        migrations.AlterField(
            model_name='shelterimage',
            name='image',
            field=models.ImageField(default='shelters/no_image.png', upload_to=shelters.utils.shelter_image_upload_path),
        ),
    ]
