# Generated by Django 5.0.14 on 2026-08-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_alter_shelter_address_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
