services:
  fur_and_feather_db:
    image: postgres:15-alpine
    container_name: fur_and_feather_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: furandfeather123
      POSTGRES_DB: fur_and_feather
    ports:
      - "5433:5432"
    networks:
      - fur_and_feather_network
    volumes:
      - fur_and_feather_pg_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
  

  fur_and_feather_app:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: fur_and_feather_app
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      fur_and_feather_db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - fur_and_feather_network


networks:
  fur_and_feather_network:
    driver: bridge

volumes:
  fur_and_feather_pg_volume: