# Generated by Django 5.0.14 on 2026-08-16 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('RABBIT', 'Rabbit'), ('OTHER', 'Other')], max_length=20)),
                ('custom_species', models.CharField(blank=True, max_length=100, null=True)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('estimated_age', models.PositiveIntegerField(blank=True, help_text='Estimated age in months if DOB is unknown.', null=True, validators=[django.core.validators.MaxValueValidator(360)])),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in kilograms.', null=True, validators=[django.core.validators.MaxValueValidator(200)])),
                ('description', models.TextField(max_length=500)),
                ('favorite_things', models.TextField(blank=True, help_text='Favorite food, toys, activities, etc.', max_length=500, null=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('UNDER_TREATMENT', 'Under Treatment'), ('SPECIAL_NEEDS', 'Special Needs')], default='HEALTHY', max_length=30)),
                ('adoption_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=20)),
                ('is_neutered', models.BooleanField(default=False)),
                ('care_recovery', models.PositiveIntegerField(blank=True, help_text='Estimated cost of care and recovery.', null=True)),
                ('intake_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='shelters.shelter')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='pets/no_image.png', upload_to='pets/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Pet Image',
                'verbose_name_plural': 'Pet Images',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='petimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('pet',), name='unique_primary_image'),
        ),
    ]
