# Generated by Django 5.2.3 on 2026-07-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('RABBIT', 'Rabbit'), ('OTHER', 'Other')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('estimated_age', models.PositiveIntegerField(blank=True, help_text='Estimated age in months if DOB is unknown.', null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('vaccinated', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('health_status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('UNDER_TREATMENT', 'Under Treatment'), ('SPECIAL_NEEDS', 'Special Needs')], default='HEALTHY', max_length=30)),
                ('adoption_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('ADOPTED', 'Adopted')], default='AVAILABLE', max_length=20)),
                ('is_neutered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
    ]
