# Generated by Django 5.0.14 on 2026-08-21 01:42

import pets.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='image',
            field=models.ImageField(default='pets/no_image.png', upload_to=pets.utils.pet_image_upload_path),
        ),
    ]
