# Generated by Django 5.2.3 on 2026-07-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='custom_species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
